### ISSUE TITLE
Doesn't support iOS.

### ISSUE THREAD

**Issue by zzeitt** [BBazard/obsidian-orgmode-cm6#3]
Can't install on my iPhone 12 mini.
![image](https://github.com/BBazard/obsidian-orgmode-cm6/assets/30381410/9f3e9f41-9f7e-4bfd-b700-2534ad704a80)

**Comment by BBazard** [comment]
The plugin cannot be installed on android/ios because of this line in the manifest.json :
[`"isDesktopOnly": true`](https://github.com/BBazard/obsidian-orgmode-cm6/blob/master/manifest.json#L9)

I don't use obsidian on mobile so it's not implemented.

**Comment by zzeitt** [comment]
Change "isdesktoponly" to "false" does make it installable on iOS. But it doesn't take any effect on .org files.

**Comment by BBazard** [comment]
I took a look with android (following https://docs.obsidian.md/Plugins/Getting+started/Mobile+development), one problem is that `global` doesn't exist on mobile

https://github.com/BBazard/obsidian-orgmode-cm6/blob/58c93807e25f8a74b2f157434c3370bd2bc3af02/main.ts#L85-L86
This is the way the plugin allows you to change the settings without reloading the codemirror extension, and allows other plugins to have access to those settings.

So yes, currently it just doesn't work on mobile devices.

I think we could make it work by using codemirror [compartments](https://codemirror.net/examples/config/#compartments) but I am not sure when I will have the time to make the change, and maybe there is other issues on mobile.

**Comment by zzeitt** [comment]
Well, thanks for your reply! I am not familiar with obsidian plugin developing, so little help can I offer. But I will keep tracking this issue.

**Comment by BBazard** [comment]
I released 2.0.0 with mobile support.

I tested it on android, can you tell me if it works on your side with iOS?

**Comment by zzeitt** [comment]
It works! Thanks!
![image](https://github.com/BBazard/obsidian-orgmode-cm6/assets/30381410/2a0e5196-3374-4c05-a519-c9ebae95e46c)![image](https://github.com/BBazard/obsidian-orgmode-cm6/assets/30381410/4d984620-d617-4471-aed3-7fe1f5c99768)
Nice to see that orgmode invade Obsidian successfully 😈.

**Comment by zzeitt** [comment]
By the way, there is only source/edit mode in orgmode view. Can we support something like "markdown preview" in orgmode view?

**Comment by BBazard** [comment]
Possible to implement with [decorations](https://codemirror.net/examples/decoration), but everything has to be done from scratch since obsidian is not open source.

**Comment by zzeitt** [comment]
Okay, will give more try in editing mode. Thank you!
