### ISSUE TITLE
Org files use Vim bindings but I don't have Vim bindings enabled

### ISSUE THREAD

**Issue by jackbaty** [BBazard/obsidian-orgmode-cm6#5]
When opening an .org file in Obsidian, the plugin does a nice job of highlighting, etc. But it also seems to start out using Vim bindings, even though I have Vim key bindings disabled. Is this a CM setting/issue with the plugin? 

Is there a way to *not* enable Vim bindings by default when editing .org documents? Perhaps it could follow the built-in "Vim key bindings" setting.

Thanks

**Comment by BBazard** [comment]
Thank you for taking the time to open an issue :slightly_smiling_face: 

With the release 2.2.1, vim mode in orgmode follow the obsidian settings.

**Comment by jackbaty** [comment]
Works great now, thanks!
