### ISSUE TITLE
image link doesn't open on android

### ISSUE THREAD

**Issue by sahilkmishra** [BBazard/obsidian-orgmode-cm6#9]
I'm sure this is on your radar but a handful of my org files won't open, I suspect it has to do with image and shell links I use.

**Comment by BBazard** [comment]
If only some of your org files won't open, it's most likely because of an error while parsing the file.

Could you send me a example of a file which doesn't work? You can try removing lines to generate a minimal example that doesn't open. If I have an example I can fix it.

**Comment by sahilmishra** [comment]
heres an example file with three errors:
```#+title: android test

* Test
** Commands
*** [[shell:kitty --detach nvim --listen /tmp/godot.pipe][open nvim]]
** Ideas
***** [[https://pinballmakers.com/wiki/images/2/27/Visual-pinball.png]]
******
```

the shell, image, and blank header all cause the plugin to fail loading

**Comment by sahilkmishra** [comment]
lol sorry about switching accounts, I essentially dont care if the shell links do anything, I just have them for desktop use

**Comment by BBazard** [comment]
Thanks for the example, I could reproduce easily :+1:
I released 2.5.4 which fixes the problem on my side.

**Comment by sahilkmishra** [comment]
Amazing it works for me as well!

I ran into one more error a blank TODO:
```
** TODO 
```

this also results in a crash, I imagine it is the same for DONE. etc

**Comment by BBazard** [comment]
Nice catch :slightly_smiling_face: 
Tell me what you think of release 2.5.5

**Comment by sahilkmishra** [comment]
everything is working thank you!!
